# Generated by Django 4.1.3 on 2023-01-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categ_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
